### ISSUE TITLE
pi deploy fails class not found exception 

### ISSUE THREAD

**Issue by pkandathil** [PredictionIO/template-java-parallel-ecommercerecommendation#1]
Hi, 

I follow all the instructions in the quick start guide lo
cated here https://docs.prediction.io/templates/javaecommercerecommendation/quickstart/

The engine trains fine and I am able to deploy it. When I make a curl request to the engine, I get this exception:

```
java.lang.NoClassDefFoundError: org/jblas/DoubleMatrix

```

**Comment by EmergentOrder** [comment]
Fixed in PR #2
